
import { JCD_V3_PROJECT_ENUM } from './jcd-v3-project-enum';

export enum JCD_V3_IMAGE_TYPE {
  TITLE = 'TITLE',
  GALLERY = 'GALLERY',
}

export type JcdV3ImageProjectBase = {
  projectKey: JCD_V3_PROJECT_ENUM,
  titleImgUri: string;
  galleryImgUris: string[];
};

export const JCD_V3_IMAGE_PROJECT_BASES: JcdV3ImageProjectBase[] = [
  {
    projectKey: JCD_V3_PROJECT_ENUM.BALTHAZAR,
    titleImgUri: 'balthazar/00-Balthazar.jpg',
    galleryImgUris: [
      'balthazar/01-Balthazar.jpg',
      'balthazar/02-Balthazar.jpg',
      'balthazar/03-Balthazar.jpg',
      'balthazar/04-Balthazar.jpg',
      'balthazar/05-Balthazar.jpg',
      'balthazar/06-Balthazar.jpg',
      'balthazar/07-Balthazar.jpg',
      'balthazar/08-Balthazar.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.THE_DIARY_OF_ANNE_FRANK,
    titleImgUri: 'anne-frank/00-Anne-Frank.jpg',
    galleryImgUris: [
      'anne-frank/01-Anne-Frank.jpg',
      'anne-frank/02-Anne-Frank.jpg',
      'anne-frank/03-Anne-Frank.jpg',
      'anne-frank/04-Anne-Frank.jpg',
      'anne-frank/05-Anne-Frank.jpg',
      'anne-frank/06-Anne-Frank.jpg',
      'anne-frank/07-Anne-Frank.jpg',
      'anne-frank/08-Anne-Frank.jpg',
      'anne-frank/09-Anne-Frank.jpg',
      'anne-frank/10-Anne-Frank.jpg',
      'anne-frank/11-Anne-Frank.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.GO_HOME_COME_BACK,
    titleImgUri: 'go-home/00-Go-Home.jpg',
    galleryImgUris: [
      'go-home/01-Go-Home.jpg',
      'go-home/02-Go-Home.jpg',
      'go-home/03-Go-Home.jpg',
      'go-home/04-Go-Home.jpg',
      'go-home/05-Go-Home.jpg',
      'go-home/06-Go-Home.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.THE_TALES_OF_HOFFMANN,
    titleImgUri: '1-hoffman/00-hoffmann-title.jpg',
    galleryImgUris: [
      '1-hoffman/01-hoffmann.jpg',
      '1-hoffman/02-hoffmann.jpg',
      '1-hoffman/03-hoffmann.jpg',
      '1-hoffman/04-hoffmann.jpg',
      '1-hoffman/05-hoffmann.jpg',
      '1-hoffman/06-hoffmann.jpg',
      '1-hoffman/07-hoffmann.jpg',
      '1-hoffman/08-hoffmann.jpg',
      '1-hoffman/09-hoffmann.jpg',
      '1-hoffman/10-hoffmann.jpg',
      '1-hoffman/11-hoffmann.jpg',
      '1-hoffman/12-hoffmann.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.LARAMIE_PROJECT,
    titleImgUri: '2-laramie/00-laramie-title.jpg',
    galleryImgUris: [
      '2-laramie/01-laramie.jpg',
      '2-laramie/02-laramie.jpg',
      '2-laramie/03-laramie.jpg',
      '2-laramie/04-laramie.jpg',
      '2-laramie/05-laramie.jpg',
      '2-laramie/06-laramie.jpg',
      '2-laramie/07-laramie.jpg',
      '2-laramie/08-laramie.jpg',
      '2-laramie/09-laramie.jpg',
      '2-laramie/10-laramie.jpg',
      '2-laramie/11-laramie.jpg',
      '2-laramie/12-laramie.jpg',
      '2-laramie/13-laramie.jpg',
      '2-laramie/14-laramie.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.MY_BROTHER_WAS_A_VAMPIRE,
    titleImgUri: '3-vampire/00-vampire-title.jpg',
    galleryImgUris: [
      '3-vampire/01-vampire.jpg',
      '3-vampire/02-vampire.jpg',
      '3-vampire/03-vampire.jpg',
      '3-vampire/04-vampire.jpg',
      '3-vampire/05-vampire.jpg',
      '3-vampire/06-vampire.jpg',
      '3-vampire/07-vampire.jpg',
      '3-vampire/08-vampire.jpg',
      '3-vampire/09-vampire.jpg',
      '3-vampire/10-vampire.jpg',
      '3-vampire/11-vampire.jpg',
      '3-vampire/12-vampire.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.LA_BOHEME,
    titleImgUri: '4-boheme/00-boheme-title.jpg',
    galleryImgUris: [
      '4-boheme/01-boheme.jpg',
      '4-boheme/02-boheme.jpg',
      '4-boheme/03-boheme.jpg',
      '4-boheme/04-boheme.jpg',
      '4-boheme/05-boheme.jpg',
      '4-boheme/06-boheme.jpg',
      '4-boheme/07-boheme.jpg',
      '4-boheme/08-boheme.jpg',
      '4-boheme/09-boheme.jpg',
      '4-boheme/10-boheme.jpg',
      '4-boheme/11-boheme.jpg',
      '4-boheme/12-boheme.jpg',
      '4-boheme/13-boheme.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.URINETOWN,
    titleImgUri: '5-urinetown/00-urinetown-title.jpg',
    galleryImgUris: [
      '5-urinetown/01-urinetown.jpg',
      '5-urinetown/02-urinetown.jpg',
      '5-urinetown/03-urinetown.jpg',
      '5-urinetown/04-urinetown.jpg',
      '5-urinetown/05-urinetown.jpg',
      '5-urinetown/06-urinetown.jpg',
      '5-urinetown/07-urinetown.jpg',
      '5-urinetown/08-urinetown.jpg',
      '5-urinetown/09-urinetown.jpg',
      '5-urinetown/10-urinetown.jpg',
      '5-urinetown/11-urinetown.jpg',
      '5-urinetown/12-urinetown.jpg',
      '5-urinetown/13-urinetown.jpg',
      '5-urinetown/14-urinetown.jpg',
      '5-urinetown/15-urinetown.jpg',
      '5-urinetown/16-urinetown.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.THE_TEMPEST,
    titleImgUri: '6-tempest/00-tempest-title.jpg',
    galleryImgUris: [
      '6-tempest/01-tempest.jpg',
      '6-tempest/02-tempest.jpg',
      '6-tempest/03-tempest.jpg',
      '6-tempest/04-tempest.jpg',
      '6-tempest/05-tempest.jpg',
      '6-tempest/06-tempest.jpg',
      '6-tempest/07-tempest.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.AFTERSHOCK,
    titleImgUri: '7-aftershock/00-aftershock-title.jpg',
    galleryImgUris: [
      '7-aftershock/01-aftershock.jpg',
      '7-aftershock/02-aftershock.jpg',
      '7-aftershock/03-aftershock.jpg',
      '7-aftershock/04-aftershock.jpg',
      '7-aftershock/05-aftershock.jpg',
      '7-aftershock/06-aftershock.jpg',
      '7-aftershock/07-aftershock.jpg',
      '7-aftershock/08-aftershock.jpg',
      '7-aftershock/09-aftershock.jpg',
      '7-aftershock/10-aftershock.jpg',
      '7-aftershock/11-aftershock.jpg',
      '7-aftershock/12-aftershock.jpg',
      '7-aftershock/13-aftershock.jpg',
      '7-aftershock/14-aftershock.jpg',
      '7-aftershock/15-aftershock.jpg',
      '7-aftershock/16-aftershock.jpg',
      '7-aftershock/17-aftershock.jpg',
      '7-aftershock/18-aftershock.jpg',
      '7-aftershock/19-aftershock.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.SWEENEY_TODD,
    titleImgUri: '8-sweeney/00-sweeney-title.jpg',
    galleryImgUris: [
      '8-sweeney/01-sweeney.jpg',
      '8-sweeney/02-sweeney.jpg',
      '8-sweeney/03-sweeney.jpg',
      '8-sweeney/04-sweeney.jpg',
      '8-sweeney/05-sweeney.jpg',
      '8-sweeney/06-sweeney.jpg',
      '8-sweeney/07-sweeney.jpg',
      '8-sweeney/08-sweeney.jpg',
      '8-sweeney/09-sweeney.jpg',
      '8-sweeney/10-sweeney.jpg',
      '8-sweeney/11-sweeney.jpg',
      '8-sweeney/12-sweeney.jpg',
      '8-sweeney/13-sweeney.jpg',
      '8-sweeney/14-sweeney.jpg',
      '8-sweeney/15-sweeney.jpg',
      '8-sweeney/16-sweeney.jpg',
      '8-sweeney/17-sweeney.jpg',
      '8-sweeney/18-sweeney.jpg',
    ],
  },
  // {
  //   projectKey: JCD_V3_PROJECT_ENUM.O_DEAR_BLOSSOM,
  //   titleImgUri: '',
  //   galleryImgUris: [

  //   ],
  // },
  {
    projectKey: JCD_V3_PROJECT_ENUM.JAMES_AND_THE_GIANT_PEACH,
    titleImgUri: '10-james-and-the-giant-peach/00-james-title.jpg',
    galleryImgUris: [
      '10-james-and-the-giant-peach/01-james.jpg',
      '10-james-and-the-giant-peach/02-james.jpg',
      '10-james-and-the-giant-peach/03-james.jpg',
      '10-james-and-the-giant-peach/04-james.jpg',
      '10-james-and-the-giant-peach/05-james.jpg',
      '10-james-and-the-giant-peach/06-james.jpg',
      '10-james-and-the-giant-peach/07-james.jpg',
      '10-james-and-the-giant-peach/08-james.jpg',
      '10-james-and-the-giant-peach/09-james.jpg',
      '10-james-and-the-giant-peach/10-james.jpg',
      '10-james-and-the-giant-peach/11-james.jpg',
      '10-james-and-the-giant-peach/12-james.jpg',
      '10-james-and-the-giant-peach/13-james.jpg',
      '10-james-and-the-giant-peach/14-james.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.THE_DRAG,
    titleImgUri: '11-the-drag/00-drag-title.jpg',
    galleryImgUris: [
      '11-the-drag/01-drag.jpg',
      '11-the-drag/02-drag.jpg',
      '11-the-drag/03-drag.jpg',
      '11-the-drag/04-drag.jpg',
      '11-the-drag/05-drag.jpg',
      '11-the-drag/06-drag.jpg',
      '11-the-drag/07-drag.jpg',
      '11-the-drag/08-drag.jpg',
      '11-the-drag/09-drag.jpg',
      '11-the-drag/10-drag.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.AGAMEMNON,
    titleImgUri: '12-agamemnon/00-agamemnon-title.jpg',
    galleryImgUris: [
      '12-agamemnon/01-agamemnon.jpg',
      '12-agamemnon/02-agamemnon.jpg',
      '12-agamemnon/03-agamemnon.jpg',
      '12-agamemnon/04-agamemnon.jpg',
      '12-agamemnon/05-agamemnon.jpg',
      '12-agamemnon/06-agamemnon.jpg',
      '12-agamemnon/07-agamemnon.jpg',
      '12-agamemnon/08-agamemnon.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.CINDERELLA_EATS_RICE_AND_BEANS,
    titleImgUri: '13-cinderella-eats-rice-and-beans/00-cinderella-title.jpg',
    galleryImgUris: [
      '13-cinderella-eats-rice-and-beans/01-cinderella.jpg',
      '13-cinderella-eats-rice-and-beans/02-cinderella.jpg',
      '13-cinderella-eats-rice-and-beans/03-cinderella.jpg',
      '13-cinderella-eats-rice-and-beans/04-cinderella.jpg',
      '13-cinderella-eats-rice-and-beans/05-cinderella.jpg',
      '13-cinderella-eats-rice-and-beans/06-cinderella.jpg',
      '13-cinderella-eats-rice-and-beans/07-cinderella.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.THE_CLEAN_UP_PROJECT,
    titleImgUri: '14-the-clean-up-project/00-clean-up-title.jpg',
    galleryImgUris: [
      '14-the-clean-up-project/01-clean-up.jpg',
      '14-the-clean-up-project/02-clean-up.jpg',
      '14-the-clean-up-project/03-clean-up.jpg',
      '14-the-clean-up-project/04-clean-up.jpg',
      '14-the-clean-up-project/05-clean-up.jpg',
      '14-the-clean-up-project/06-clean-up.jpg',
      '14-the-clean-up-project/07-clean-up.jpg',
      '14-the-clean-up-project/08-clean-up.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.NEXT_FALL,
    titleImgUri: '15-next-fall/00-next-fall-title.jpg',
    galleryImgUris: [
      '15-next-fall/01-next-fall.jpg',
      '15-next-fall/02-next-fall.jpg',
      '15-next-fall/03-next-fall.jpg',
      '15-next-fall/04-next-fall.jpg',
      '15-next-fall/05-next-fall.jpg',
      '15-next-fall/06-next-fall.jpg',
      '15-next-fall/07-next-fall.jpg',
      '15-next-fall/08-next-fall.jpg',
      '15-next-fall/09-next-fall.jpg',
      '15-next-fall/10-next-fall.jpg',
    ],
  },
  {
    projectKey: JCD_V3_PROJECT_ENUM.TRIBES,
    titleImgUri: '16-tribes/00-tribes-title.jpg',
    galleryImgUris: [
      '16-tribes/01-tribes.jpg',
      '16-tribes/02-tribes.jpg',
      '16-tribes/03-tribes.jpg',
      '16-tribes/04-tribes.jpg',
      '16-tribes/05-tribes.jpg',
      '16-tribes/06-tribes.jpg',
      '16-tribes/07-tribes.jpg',
    ],
  },
];
