
import { JcdV3ProjectKey } from '../../models/jcd-models-v3/jcd-v3-project-key';

/*
  AGAMEMNON
  agamemnon

  CABARET
  cabaret

  CINDERELLA
  cinderella

  FAT_PIG
  fat-pig

  JAMES_AND_THE_GIANT_PEACH
  james-and-the-giant-peach

  LARAMIE
  the-laramie-project

  MRBURNS
  mr-burns

  NEXT_FALL
  next-fall

  SUNDANCE
  joseph-and-the-amazing-technicolor-dreamcoat

  SWEENEY
  sweeney-todd

  TAMINGOFTHESHREW
  taming-of-the-shrew

  THE_DRAG
  the-drag

  TRIBES
  tribes

  URINETOWN
  urinetown-the-musical

  UVU
  a-year-with-frog-and-toad
*/

export enum JCD_V3_PROJECT_ENUM {

  THE_TALES_OF_HOFFMANN = 'THE_TALES_OF_HOFFMANN',
  LARAMIE_PROJECT = 'LARAMIE_PROJECT',
  MY_BROTHER_WAS_A_VAMPIRE = 'MY_BROTHER_WAS_A_VAMPIRE',
  LA_BOHEME = 'LA_BOHEME',
  URINETOWN = 'URINETOWN',
  THE_TEMPEST = 'THE_TEMPEST',
  AFTERSHOCK = 'AFTERSHOCK',
  SWEENEY_TODD = 'SWEENEY_TODD',
  O_DEAR_BLOSSOM = 'O_DEAR_BLOSSOM',
  JAMES_AND_THE_GIANT_PEACH = 'JAMES_AND_THE_GIANT_PEACH',
  THE_DRAG = 'THE_DRAG',
  AGAMEMNON = 'AGAMEMNON',
  CINDERELLA_EATS_RICE_AND_BEANS = 'CINDERELLA_EATS_RICE_AND_BEANS',
  THE_CLEAN_UP_PROJECT = 'THE_CLEAN_UP_PROJECT',
  NEXT_FALL = 'NEXT_FALL',
  TRIBES = 'TRIBES',

  // TAMINGOFTHESHREW = 'TAMINGOFTHESHREW',
  // MRBURNS = 'MRBURNS',
  // FAT_PIG = 'FAT_PIG',
  // A_YEAR_WITH_FROG_AND_TOAD = 'A_YEAR_WITH_FROG_AND_TOAD', // Formerly UVU
  // SUNDANCE_TECHNICOLOR_DREAMCOAT = 'SUNDANCE_TECHNICOLOR_DREAMCOAT',
  // CABARET = 'CABARET',

  // RENAISSANCE_NOW = 'RENAISSANCE_NOW',
  // BYU = 'BYU',
  // RENAISSANCE_FAIRE = 'RENAISSANCE_FAIRE',
}

export const JCD_V3_PROJECT_LIST: JCD_V3_PROJECT_ENUM[] = [
  JCD_V3_PROJECT_ENUM.THE_TALES_OF_HOFFMANN,
  JCD_V3_PROJECT_ENUM.LARAMIE_PROJECT,
  JCD_V3_PROJECT_ENUM.MY_BROTHER_WAS_A_VAMPIRE,
  JCD_V3_PROJECT_ENUM.LA_BOHEME,
  JCD_V3_PROJECT_ENUM.URINETOWN,
  JCD_V3_PROJECT_ENUM.THE_TEMPEST,
  JCD_V3_PROJECT_ENUM.AFTERSHOCK,
  JCD_V3_PROJECT_ENUM.SWEENEY_TODD,
  // JCD_V3_PROJECT_ENUM.O_DEAR_BLOSSOM,
  JCD_V3_PROJECT_ENUM.JAMES_AND_THE_GIANT_PEACH,
  JCD_V3_PROJECT_ENUM.THE_DRAG,
  JCD_V3_PROJECT_ENUM.AGAMEMNON,
  JCD_V3_PROJECT_ENUM.CINDERELLA_EATS_RICE_AND_BEANS,
  JCD_V3_PROJECT_ENUM.THE_CLEAN_UP_PROJECT,
  JCD_V3_PROJECT_ENUM.NEXT_FALL,
  JCD_V3_PROJECT_ENUM.TRIBES,
];
